/*
    test_avalanche.c

    Test the Pa55w0rd Avalanche function

    (CC) Creative Commons 2025 by Guillermo Amodeo Ojeda.

    I dedicate the software in this file to the public domain, so it is entirely free.
    Thus you may use it and/or redistribute it for whatever purpose you may choose.

    It is actually distributed with the hope that it would be useful to someone,
    but with no guarantee whatsoever. Not even the guarantee that it will work.

    Also, being free software, it is provided without warranty of any kind,
    not even the implied warranty of merchantability or fitness for a particular
    purpose. I also disclaim any liability arising from any use of this software.

    Read the CC license at https://creativecommons.org/publicdomain/zero/1.0/

    NOTES:

        - Written by Guillermo Amodeo Ojeda.                  
            
                        --oO0Oo--
*/

#include "avalanche.h"

#define NUM_WORDS 50

const char *words[NUM_WORDS] =
{
     "a",
	 "atmosphere",     
	 "basketball", 
     "bury",
	 "concentration", 
     "copy", 
	 "dog", 
     "dramatically", 
	 "establishment",
     "ever", 
	 "frustration",
	 "fund", 
     "grandfather",
	 "go",
	 "hi",
	 "hypothesis",
     "I",
	 "involvement",     	 
	 "joke", 
     "journalist",
     "keep",
     "kangaroo",
	 "literature",
	 "low", 	 
	 "moon", 
     "motivation",	 
	 "near", 
     "negotiation",
	 "otherwise", 
	 "own",
	 "punishment", 
	 "put", 
     "quarterback", 	 
     "quit", 
	 "responsible",
	 "rise",  	 
	 "specifically",
	 "spot", 
	 "tremendous",
	 "trust",
	 "ugly",
	 "utility",
	 "vast", 	 
	 "visible",
	 "whatever",
	 "window",
	 "yard",
	 "yourself",
     "zulu",
     "zachary",
};




int main(int argc,char **argv)
{
    int t,len = 35;
    char str[256] = {0};

    if(argc < 3)
        printf("\n**** Test of pa55w0rd_avalanche() ****\n\n");

    if(argc > 1)
    {
        len = atoi(argv[1]);
        if(len < 8 || len > 250)
        {
            printf("usage: %s  [num_chars] [[word or \"quoted sentence to avalanche\"] ... ]"
                   "\n\nWhere num_chars is the number of chars generated by the function (8 - 250)\n\n",argv[0]);
            return -1;
        }        
        if(argc > 2)
        {            
            for(t=2;t<argc;t++)
                printf("%d - %s\n",len,pa55w0rd_avalanche(argv[t],str,len + 1));   
            printf("\n");
            return 0;
        }
    }
    
    printf("pa55w0rd_avalanche(%13s) = %d - %s\n","",len, pa55w0rd_avalanche("",str,len + 1));   
    for(t=0; t<NUM_WORDS; t++)
        printf("pa55w0rd_avalanche(%13s) = %d - %s\n",words[t],len, pa55w0rd_avalanche(words[t],str,len + 1));   
    printf("\n");

    return 0;
}